version: 2

updates:

  - package-ecosystem: pip
    # setup.py stored in repository root.
    directory: '/'
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: develop
    schedule:
      # Check for updates managed by pip once a week
      interval: weekly
    # Specify labels for npm pull requests
    labels:
      - pip
      - dependencies
    assignees:
      - sergeyklay

  - package-ecosystem: github-actions
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: develop
    schedule:
      # Check for updates for GitHub actions once a week
      interval: weekly
    # Specify labels for npm pull requests
    labels:
      - github_actions
      - dependencies
    assignees:
      - sergeyklay
