language: python
dist: xenial
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "nightly"
 - "pypy"
env:
  - DJANGO="1.8"
  - DJANGO="1.9"
  - DJANGO="1.10"
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="2.1"
  - DJANGO="2.2"
  - DJANGO="master"
matrix:
  fast_finish: true
  exclude:
    - python: 2.7
      env: DJANGO="2.0"

    - python: 2.7
      env: DJANGO="2.1"

    - python: 2.7
      env: DJANGO="master"

    - python: 3.4
      env: DJANGO="2.1"

    - python: 3.4
      env: DJANGO="master"

    - python: 3.5
      env: DJANGO="master"
  allow_failures:
  	- env: DJANGO="master"

install:
 # The default pip doesn't properly support pre-release version specifiers.
 - pip install -U pip
 - pip install tox
 - pip install -q tox-travis
branches:
 only:
  - master
  - develop
  - /^feature\/.+/
  - /^release\/.+/
  - /^hotfix\/.+/
  - /^v[\d\.]+/
script: tox
after_success:
  - pip install --quiet python-coveralls
  - coveralls
