version: ~> 1.0
language: python
os: linux
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8-dev"
 - "nightly"
 - "pypy"
jobs:
  matrix:
   - DJANGO="Django==1.11.*"
   - DJANGO="Django==2.0.*"
   - DJANGO="Django==2.1.*"
   - DJANGO="Django==2.2.*"
   - DJANGO="https://github.com/django/django/archive/master.tar.gz"
install:
 # The default pip doesn't properly support pre-release version specifiers.
 - pip install -U pip
 - pip install . coverage $DJANGO
branches:
 only:
  - master
  - develop
  - /^feature\/.+/
  - /^release\/.+/
  - /^hotfix\/.+/
  - /^v[\d\.]+/
script: coverage run --source=environ setup.py test
jobs:
  fast_finish: true
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
