language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "nightly"
env:
  matrix:
   - DJANGO="Django>=1.8,<1.9"
   - DJANGO="Django>=1.9,<1.10"
   - DJANGO="Django>=1.10,<1.11"
install:
 - pip install $DJANGO
 - pip install .
 - pip install coverage
branches:
 only:
  - master
  - develop
  - /^feature\/.+/
  - /^release\/.+/
  - /^hotfix\/.+/
  - /^v[\d\.]+/
script: coverage run --source=environ setup.py test
matrix:
  include:
    - python: "3.3"
      env: DJANGO="Django>=1.8,<1.9"
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
