language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
env:
  matrix:
   - DJANGO=Django==1.4
   - DJANGO=Django==1.5
   - DJANGO="git+git://github.com/django/django.git@stable/1.6.x#egg=django"
install:
 - pip install $DJANGO --use-mirrors
 - pip install . --use-mirrors
 - pip install coverage
branches:
 only:
  - master
  - develop
script: coverage run --source=environ setup.py test
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=Django==1.4
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
