# https://ci.appveyor.com/project/joke2k/django-environ
build: false
environment:
  PYTHONIOENCODING: "utf-8"
  matrix:
    - PYTHON: "C:/Python38"
      DJANGO_VERSION: "Django==1.8.*"

    - PYTHON: "C:/Python38"
      DJANGO_VERSION: "Django==1.9.*"

    - PYTHON: "C:/Python38"
      DJANGO_VERSION: "Django==1.10.*"

    - PYTHON: "C:/Python38"
      DJANGO_VERSION: "Django==1.11.*"

    - PYTHON: "C:/Python38"
      DJANGO_VERSION: "Django==2.0.*"

    - PYTHON: "C:/Python38"
      DJANGO_VERSION: "Django==2.1.*"

    - PYTHON: "C:/Python38"
      DJANGO_VERSION: "Django==2.2.*"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - ps: |
      [Net.ServicePointManager]::SecurityProtocol = 'Tls11, Tls12'
      (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install \"%DJANGO_VERSION%\""
  - "%PYTHON%/Scripts/pip.exe install -e ."
test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/python.exe setup.py test"
