name: Docs

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
      - 'release/**'
      - 'fix/**'

  # The branches below must be a subset of the branches above
  pull_request:
    branches:
      - develop
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Build and test package documentation

    # The maximum number of minutes to let a workflow run
    # before GitHub automatically cancels it. Default: 360
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Check external links in the package documentation
        run: tox -e linkcheck

      - name: Build and test package documentation
        run: tox -e docs

      - name: Archive docs artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs
          # Artifacts are retained for 90 days by default.
          # In fact, we don't need such long period.
          retention-days: 60
